# Generated by Django 2.1.3 on 2018-12-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
