# Generated by Django 2.1.3 on 2018-12-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181210_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messae',
            new_name='message',
        ),
    ]
